ab_mode=-1
blueprint_path=['/routes']
db_pool_exe_time=False
debug_trace=False
error_info='HTML'
host='127.0.0.1'
ip_count=False
mq={'remote_center': False}
msg_queue_debug=False
msg_queue_max_num=30
pool_conn_num=5
port=443
project_root='F:/person/dophon/test3'
pydc_xmlupdate_sech=False
server_processes=1
server_threaded=True
ssl_context='adhoc'
